%This initializes all the fibertypes. The fibertypes are registered as an
%equality matrix, meaning that entry (i,j) is zero if i is different from j
%and one if i and j are the same point.

matrix = eye(4);
threeZero = fiberType([matrix zeros(4); zeros(4) matrix], 30);
matrix(1,2) = 1;
M = matrix + transpose(matrix) - diag(diag(matrix));
N = M;
N(3,3) = 0;
N(4,4) = 0;
twoZero = fiberType([M zeros(4); zeros(4) M], 20);
twoOne = fiberType([M N; N M], 21);
matrix(1,3) = 1;
matrix(2,3) = 1;
M = matrix + transpose(matrix) - diag(diag(matrix));
O = M;
O(4,4) = 0;
oneZero = fiberType([M zeros(4); zeros(4) M], 10);
oneOne = fiberType([M O; O M], 11);
matrix = eye(4);
matrix(1,2) = 1;
matrix(3,4) = 1;
M = matrix + transpose(matrix) - diag(diag(matrix));
fourZero = fiberType([M zeros(4); zeros(4) M], 40);
fourOne = fiberType([M N; N M], 41);
fourTwo = fiberType([M M;M M], 42);
fourTwo.setMatrix([M M;M M], [M M;M M]);
fiveZero = fiberType([ones(4) zeros(4); zeros(4) ones(4)], 50);
fiveOne = fiberType(ones(8), 51);
%Here we use the characterictic polynomial of the matrices to recognize
%them
identificationMatrix = zeros(10, 9);
identificationMatrix(1,:) = charpoly(fiveOne.pointsArray);
identificationMatrix(2,:) = charpoly(fiveZero.pointsArray);
identificationMatrix(3,:) = charpoly(oneOne.pointsArray);
identificationMatrix(4,:) = charpoly(oneZero.pointsArray);
identificationMatrix(5,:) = charpoly(threeZero.pointsArray);
identificationMatrix(6,:) = charpoly(fourOne.pointsArray);
identificationMatrix(7,:) = charpoly(fourTwo.pointsArray);
identificationMatrix(8,:) = charpoly(fourZero.pointsArray);
identificationMatrix(9,:) = charpoly(twoOne.pointsArray);
identificationMatrix(10,:) = charpoly(twoZero.pointsArray);
identificationMatrix = identificationMatrix(:,3) + identificationMatrix(:,4);
%Here we encode the types of the output of the Donagi construction
threeZero.setOutputs(threeZero, threeZero);
twoZero.setOutputs(twoZero, twoZero);
twoOne.setOutputs(fourZero, fourZero);
fourZero.setOutputs(twoOne, fourZero);
fourOne.setOutputs(fourOne, fourOne);
fourTwo.setOutputs(fourTwo, fourTwo);
oneZero.setOutputs(oneZero, oneZero);
oneOne.setOutputs(fiveZero, fiveZero);
fiveZero.setOutputs(oneOne, fiveZero);
fiveOne.setOutputs(fiveOne, fiveOne);

%Here we encode one permutation of the indices that turns the fiber type as
%encoded in the computer in the real output of the Donagi construction.
matrix = eye(8);
threeZero.setMatrix(matrix, matrix);
matrix(3,8) = 1;
matrix(4,7) = 1;
M = matrix + transpose(matrix) - diag(diag(matrix));
twoZero.setMatrix(M, M);
matrix(1,6) = 1;
matrix(2,5) = 1;
M = matrix + transpose(matrix) - diag(diag(matrix));
twoOne.setMatrix(M, M);
matrix(1,6) = 0;
matrix(2,5) = 0;
matrix(1,2) = 1;
matrix(5,6) = 1;
N = matrix + transpose(matrix) - diag(diag(matrix));
matrix(1,2) = 0;
matrix(5,6) = 0;
matrix(3,4) = 1;
matrix(3,7) = 1;
matrix(4,8) = 1;
matrix(7,8) = 1;
M = matrix + transpose(matrix) - diag(diag(matrix));
fourZero.setMatrix(M, N);
matrix(1,6) = 1;
matrix(2,5) = 1;
M = matrix + transpose(matrix) - diag(diag(matrix));
matrix(3,4) = 0;
matrix(3,7) = 0;
matrix(4,8) = 0;
matrix(7,8) = 0;
matrix(1,2) = 1;
matrix(1,5) = 1;
matrix(2,6) = 1;
matrix(5,6) = 1;
N = matrix + transpose(matrix) - diag(diag(matrix));
fourOne.setMatrix(M, N);
matrix = eye(8);
matrix(3,8) = 1;
matrix(4,7) = 1;
matrix(2,3) = 1;
matrix(2,8) = 1;
matrix(4,6) = 1;
matrix(6,7) = 1;
M = matrix + transpose(matrix) - diag(diag(matrix));
oneZero.setMatrix(M, M);
matrix(5,8) = 1;
matrix(1,4) = 1;
matrix(3,5) = 1;
matrix(2,5) = 1;
matrix(1,6) = 1;
matrix(1,7) = 1;
M = matrix + transpose(matrix) - diag(diag(matrix));
oneOne.setMatrix(M, M);
N = M;
matrix(5,8) = 0;
matrix(1,4) = 0;
matrix(3,5) = 0;
matrix(2,5) = 0;
matrix(1,6) = 0;
matrix(1,7) = 0;
matrix(2,4) = 1;
matrix(2,6) = 1;
matrix(2,7) = 1;
matrix(3,4) = 1;
matrix(3,6) = 1;
matrix(3,7) = 1;
matrix(4,8) = 1;
matrix(6,8) = 1;
matrix(7,8) = 1;
M = matrix + transpose(matrix) - diag(diag(matrix));
N = permutationToMatrix([5;2;3;4;1;6;7;8])*N*permutationToMatrix([5;2;3;4;1;6;7;8]);
fiveZero.setMatrix(M, N);
fiveOne.setMatrix(ones(8), ones(8));